### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arekpytka2812** [arekpytka2812/Taskify-Application#6]
Services:
- [ ]  task expiration timers - LOW PR
- [x]  online / ofline check service - HIGH PR
- [x]  crud services - HIGH PR
- [ ]  asynchronous requests and data displaying - MID PR
- [ ]  auto save every X minutes - LOW PR / NTD
- [x]  file coder/encoder service - HIGH PR
- [x]  uploading info into file _ HIGH PR
- [x]  notifications
- [x]  stats update

Components:
- [x]  user left panel
- [x]  style left side panel
- [x]  style every component
- [x]  updateInfo card

Workspace Panel:
- [x] delete button HIGH
- [ ] selected card LOW

Main Center:
- [x] workspace name label HIGH
- [x] filtering task HIGH
- [x] restyle task cards MID
- [x] handle add task

Setting Panel:
- [ ] style LOW
- [ ] add to list views HIGH
- [ ] test password changing HIGH
